#!/bin/bash

set -eu
set -o pipefail

npm run lint

export RUSTFLAGS="-Dwarnings"
cargo fmt --all
cargo build --all
cargo test --all
cargo clippy --all-features --fix --allow-dirty --allow-no-vcs
cargo doc
