#!/bin/bash

set -eu
set -o pipefail

# export RUSTFLAGS="${RUSTFLAGS:-} -D warnings"

cargo fmt --all
cargo build --all
cargo test --all
cargo clippy --all-targets --all-features -- -D warnings
cargo doc
