#!/bin/bash

set -eu
set -o pipefail

export RUSTFLAGS="-D warnings"
cargo fmt --all
cargo build --all
cargo test --all
cargo clippy --all-targets --all-features --fix --allow-dirty --allow-no-vcs -- -D warnings
cargo doc
